### ISSUE TITLE
Parity bit explanation might be confusing

### ISSUE THREAD

**Issue by grallc** [thezeroalpha/compnet-notes#1]
In the error detection notes, you wrote :
`add a single bit to the end to make the number of 1s even`.

However, it might be confusing for people since the teachers wrote in the slides "Add single bit such that the number of 1’s is odd."

**Comment by thezeroalpha** [comment]
Yeah that depends on whether you're doing even parity or odd parity error detection. I guess when I took the course, we were doing even parity by default, I probably should've mentioned it explicitly in the notes at that point.

If you want to add/change something, feel free to open a PR. I saw the one you opened before but I guess you still want to fix some stuff.
